name: CreateRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Zip
      run: zip THE_GUN_TURRET.zip THE_GUN_TURRET.wad THE_GUN_TURRET.txt
    - name: Gernerate Date for Release version
      run: echo "release_date=$(date "+%Y-%m-%d-%H-%M-%S")" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        release_name: THE_GUN_TURRET ${{ env.release_date }}
        tag_name: ${{ env.release_date }}
        body: ""
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./THE_GUN_TURRET.zip
        asset_name: THE_GUN_TURRET.zip
        asset_content_type: application/zip
