name: CreateRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Zip
      run: zip -r release.zip 
    name: Create Release
      run: echo "releasing ..."
