name: CreateRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show Me
      run: ls -lha
    - name: Create Zip
      run: zip release.zip THE_GUN_TURRET.wad THE_GUN_TURRET.txt
    - name: Show Me
      run: ls -lha
    - name: Create Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
